name: Curiosidade do dia

on:
  schedule:
    - cron: "0 10 * * *"   # 10:00 UTC = 07:00 America/Sao_Paulo
  workflow_dispatch: {}     # permite rodar manualmente

permissions:
  contents: write

jobs:
  update-fact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python - <<'PY'
          import sys, subprocess
          # PyYAML está disponível como pacote; instalamos
          subprocess.check_call([sys.executable, "-m", "pip", "install", "PyYAML"])
          PY
      - name: Run script
        run: python .github/scripts/daily_fact.py
      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: atualiza curiosidade do dia"
            git push
          fi
